main_params:
  log_dir: "logs/kumore"
  seed: 12

data_params:
  csv_files: ["data/aozora.csv", "data/wiki.csv", "data/jesc.csv"]
  ctrl_codes: ["青空", "知識", "訳"]
  weights: [0.4, 0.5, 0.1]
  sp_file: "data/sp_model.model"
  col_name: "text"
  batch_size: 20
#  csv_type: "split"


model_params:
  transformer_name: "ctrl"
  config_params:
    "n_embd": 512
    "vocab_size": 30000
    "n_layer": 8
  n_gpus: 1


run_params:
  train:
    num_epochs: 1
    iter_warmup_period: 25000
    lr_factor: 5
    accumulate_step: 
    save_period: 
    test_period: 
    save_iter_period: 10000
    test_iter_period: 5000
    test_file: "data/sample.csv"
#    with_tqdm: True
#    check_point_path: "logs/test1/checkpoint/checkpoint_00004221.pth"
   
